name: ocr_scan_text
description: OCR Scan Text is a wrapper around the "Google ML kit Text Recognition" library.
version: 2.0.0
homepage: https://github.com/boursorama/ocr_scan_text

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  google_mlkit_text_recognition: ^0.14.0
  camera: ^0.11.0+2
  image: ^4.0.17
  pdf_render: ^1.4.0
  path: ^1.8.2
  path_provider: ^2.0.15
  file_picker: ^8.1.4
  image_picker: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.boursorama.ocr_scan_text.ocr_scan_text
        pluginClass: OcrScanTextPlugin
      ios:
        pluginClass: OcrScanTextPlugin
